/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinkware_florida_serial_SerialPort */

#ifndef _Included_com_thinkware_florida_serial_SerialPort
#define _Included_com_thinkware_florida_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thinkware_florida_serial_SerialPort
 * Method:    openFd
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_thinkware_florida_external_serial_SerialPort_openFd
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_thinkware_florida_serial_SerialPort
 * Method:    closeFd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thinkware_florida_external_serial_SerialPort_closeFd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
